name: TerraServerSwitcher
version: 1.0
author: TerraDevTeam
main: dev.terra.Main
api-version: 1.14
commands:
  hub:
    description: tp to hub
  survival:
    description: tp to survival
  setsurvivalteleporter:
    description: sets block to teleport players to the survival server
  setspleefteleporter:
    description: sets block to teleport players to the spleef event